import React, { Component } from 'react';
import SyntaxHighlighter from 'react-syntax-highlighter';
import { ocean } from 'react-syntax-highlighter/styles/hljs';
import "../styles/docs.scss";

class Configuration extends Component {
  render() {
    return (
      <div className="Configuration">
        <h2 id='config' className="content-head is-center"><i className="fas fa-cog" /> Configuration</h2>
        <div className="pure-g">
          <div className="pure-u-1-1">
            <p>You can restart your BITBOX, change how many addresses are generated, increase/decrease the amount of entropy used when generating a mnemonic, use a custom mnemonic/HD path and toggle cashaddr/base58 on the config screen which is available if you click on the cog icon.</p>
            <p>Adding a password let&rsquo;s you explore all 2<sup>512</sup> potential $BCH master seeds.</p>
            <h5 id='entropy'>Autogenerated mnemonic length</h5>
            <p>BITBOX can autogenerate different length mnemonics based on the amount of entropy you select. The more entropy the longer the mnemonic.</p>
            <ul>
              <li>16 bytes / 128 bits === 12 words</li>
              <li>20 bytes / 160 bits === 15 words</li>
              <li>24 bytes / 192 bits === 18 words</li>
              <li>28 bytes / 224 bits === 21 words</li>
              <li>32 bytes / 256 bits === 24 words</li>
            </ul>
            <img src='/assets/screenshot6.png' />
          </div>
        </div>
      </div>
    );
  }
}

export default Configuration;
